// Generated by scripts/vendor-mediapipe-assets.mjs. Do not edit directly.
export const MEDIAPIPE_TASKS_VISION_VERSION = '0.10.35';
export const MEDIAPIPE_TASKS_VISION_BASE_URL = `/mediapipe/tasks-vision/${MEDIAPIPE_TASKS_VISION_VERSION}`;
export const MEDIAPIPE_WASM_BASE_URL = `${MEDIAPIPE_TASKS_VISION_BASE_URL}/wasm`;

export const FACE_MODEL_PATH =
	`${MEDIAPIPE_TASKS_VISION_BASE_URL}/models/face_landmarker/float16/face_landmarker.task`;
export const POSE_MODEL_PATH =
	`${MEDIAPIPE_TASKS_VISION_BASE_URL}/models/pose_landmarker_lite/float16/pose_landmarker_lite.task`;
export const SELFIE_SEGMENTER_MODEL_PATH =
	`${MEDIAPIPE_TASKS_VISION_BASE_URL}/models/selfie_segmenter/float16/selfie_segmenter.tflite`;
export const HAIR_SEGMENTER_MODEL_PATH =
	`${MEDIAPIPE_TASKS_VISION_BASE_URL}/models/hair_segmenter/float32/hair_segmenter.tflite`;
export const SELFIE_MULTICLASS_SEGMENTER_MODEL_PATH =
	`${MEDIAPIPE_TASKS_VISION_BASE_URL}/models/selfie_multiclass_256x256/float32/selfie_multiclass_256x256.tflite`;
